[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
hex = "0.4.3"
sha2 = "0.10.9"
