[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
common = { path = "../common" }
futures-core = "0.3.31"
http-body = "1.0.1"
lazy_static = "1.5.0"
sha2 = "0.10.9"
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.15", features = ["codec"] }
